# Site settings
title: "He's"
author: "HUANG He"
description: "This is a blog for code and NLP related learning notes. Not necessarily in that order."
keywords: "NLP, Data analysis, Programming, Machine Learning, Statistics"
biography: "I'm a student of the Paris Cité University."

baseurl: ""
url: "https://huangheee.github.io/"

#twitter_username: ferreira_hugo
github_username: huangheee
#douchi_username: 
#linkedin_username: hugoserenoferreira
#facebook_username: hugo.sereno.ferreira
#google-analytics: UA-69060-5

#simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/

# Handling Reading
encoding: "utf-8"

# Conversion
excerpt_separator: '<!-- more -->'
